apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cce-ingress
  namespace: app
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - http:
        paths:
          # 모든 요청을 api-gateway로 라우팅
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8000
